"""initial schema

Revision ID: e9350056791b
Revises:
Create Date: 2026-09-04 18:30:45.876150
"""

import sqlalchemy as sa

from alembic import op

revision = "e9350056791b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "scene_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("video_key", sa.String(length=512), nullable=False),
        sa.Column("preview_key", sa.String(length=512), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("actor_slots", sa.JSON(), nullable=False),
        sa.Column("motion_presets", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_templates_tenant_slug"),
    )
    with op.batch_alter_table("scene_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scene_templates_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "render_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.Enum("FACE_SWAP", "AVATAR", name="job_kind"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "DONE", "FAILED", name="job_status"),
            nullable=False,
        ),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("output_key", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["template_id"], ["scene_templates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("render_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_render_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_render_jobs_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_render_jobs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "selfies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("selfies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_selfies_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_selfies_user_id"), ["user_id"], unique=False)

    op.create_table(
        "render_job_selfies",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("selfie_id", sa.String(length=36), nullable=False),
        sa.Column("slot", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["render_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["selfie_id"], ["selfies.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("job_id", "selfie_id"),
        sa.UniqueConstraint("job_id", "slot", name="uq_job_slot"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("render_job_selfies")
    with op.batch_alter_table("selfies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_selfies_user_id"))
        batch_op.drop_index(batch_op.f("ix_selfies_tenant_id"))

    op.drop_table("selfies")
    with op.batch_alter_table("render_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_render_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_render_jobs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_render_jobs_status"))

    op.drop_table("render_jobs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))

    op.drop_table("users")
    with op.batch_alter_table("scene_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scene_templates_tenant_id"))

    op.drop_table("scene_templates")
    op.drop_table("tenants")
    # ### end Alembic commands ###
